### ISSUE TITLE
[IDEA] Let users managing columns

### ISSUE THREAD

**Issue by besstiolle** [atude/kanbie-extension#9]
First at all : TY for this small but excellent plugin. (I'll send you a virtual hug from France for your job on it) Finally a free-not-bloated-extension for an in-app kanban !

As a huge fan of Kanban, i would like to suggest to let people managing their columns 
- At least : add/rename/delete
- But why not : Reorder columns, custom color for colums, custom icone for columns (less important) 

Another idea for later : Multi Tag Filtering

As a developper myself i'd be glad to help you if necessary. 

Thank you for keeping me informed :)

**Comment by atude** [comment]
Hey, sorry just saw this now, thanks for the ideas! 

- The ability to rename columns was added a few weeks ago. 
- As for adding columns, it's difficult to do so since chrome extensions cap the max width of extensions when shown in window. If more columns were added, users would have to scroll horizontally, which isn't ideal in the small provided space and why I've held back from it. 
- Reordering columns may be useful if you could add more columns, but without that option it's hard to justify adding that feature. 
- Customising columns sounds like a great idea, including changing icon and column colour. Although for colour, it may be test to keep it within the app themes instead for consistency. 
- Multi tag filtering sounds interesting, do you mean as in being able to select a filter and only see related tasks?

Also for any of these features/ideas, you're more than welcome to make contributions, Ill try look into them as soon as I can. Thanks!
